### PR TITLE
Qwerty1q2w dev

### PR DESCRIPTION
**Pull request by qwerty1q2w**
Hello! I suggest to use variables in code and configs.

But anyway I see errors with c hard-coded values

At least in cron container
/var/www/eramba/app/upgrade/logs/cli-error.log:#0 /var/www/eramba/app/upgrade/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(84): PDO->__construct('mysql:host=mysq...', 'docker', 'docker', Array)

### CODE REVIEW

**Comment by qwerty1q2w** [comment]
Also I suggest not calling envs in cron jobs. We call envs from .main.env before  and I suggest .env now.

**Comment by qwerty1q2w** [comment]
You may change passwords in .env to "docker". At least for working now.

**Comment by qwerty1q2w** [comment]
Changes in [crontab/crontab ](https://github.com/eramba/docker/pull/25/files#diff-1ac80e97cddc5b9dec3bf1918ad7a632d650b712ec5b22b71bf51e269a4e7ab3)probably you may change in docker image too and remove string in docker-compose file in volumes section.

**Comment by shrkz1** [comment]
I like the idea of moving those environmental values like that within the .env file, but your solution overall has some issues. In order to consider merging it, there are few changes you have to make. I made a branch out of your branch with changes that makes it work - https://github.com/eramba/docker/compare/1.x...qwerty1q2w-dev

1. Needed to remove the $ sign because my shell was evaluating it as variable and it didnt work properly https://github.com/eramba/docker/commit/b7b4e7336db0a9d694e9c5809b681ec3183a9495

image

2. When doing a docker compose with environmental values defined within the YML file, these environmental values that are within CRON container wont get propagated into the cron job. So if you tried for example to print out all environemntal values during a minute cron job like:
```
* * * * printenv > /tmp/cron-envs.txt
```
it wont contain the environemntals started with the CRON container.
The only work around i know is to have those environmental values that were defined with start of the CRON container, put into some text file and let them get loaded into the cron job. So my solution to your changes would be:
Making an entrypoint for CRON container that saves ENV values into a file:
https://github.com/eramba/docker/commit/1f3bc4e57bce622bb3c9cbbbf3ed8fd46acf5087

and running cron jobs using that file:
https://github.com/eramba/docker/commit/0158128b40221b6c5604e79cab207913c570eb27

If you merge my changes into your PR branch (or do it somewhat alike), we can test it porperly here and possibly put it into 1.x release.

**Comment by qwerty1q2w** [comment]
My attempts.
image
I will try to call printenv in cron

Errors in .env with $ is normal behavior. [You can use](https://docs.docker.com/compose/environment-variables/) a $$ (double-dollar sign) when your configuration needs a literal dollar sign.

**Comment by qwerty1q2w** [comment]
@shrkz1 New PR with your changes. https://github.com/eramba/docker/pull/26/

**Comment by shrkz1** [comment]
Hello, i wanted to point out that modifying `crontab/crontab` file does not automatically reflect changes in the application - look at screenshot below:
image
`crontab -u www-data -l` tells the actual state of crontab for www-data user

thats why in the other pull request, i had to make an entrypoint for cron container where i "initialize" the updated crontab file: https://github.com/eramba/docker/pull/26/commits/1f3bc4e57bce622bb3c9cbbbf3ed8fd46acf5087#diff-aecca9bd4875b79b177e8af0a3e93388c3b188ec97daeebce66f42126ae4f52bR9

lets continue with the other PR (https://github.com/eramba/docker/pull/26)

**Comment by shrkz1** [comment]
Im closing this in favour of https://github.com/eramba/docker/pull/26

**Pull request closed without merging**
